server:
  address: ":8080"

database:
  path: "data/keyring.db"

masterKey: "OTFjYThiZmNmMmNhZGVlMjg5MzM1ZTQyZmFhMmM3MmU="
clientId: "584573895249-qgb6lesjtvhirl0t1tl23pgkkvbioigm.apps.googleusercontent.com"
owner: "izboran@gmail.com"